<?php
/**
 * Created by PhpStorm.
 * User: Ruben Hazenbosch
 * Date: 4-8-2016
 * Time: 16:42
 */

use app\lib\Calculator;
use app\lib\Project;

$calculators = ( new Calculator( "getAllCalculatorsByUser" ) )->request( $params = null );
$sessionCalculatorId = ( isset( $_SESSION['calculator_id'] ) ? $_SESSION['calculator_id'] : "" );

?>
<div class="models">
    <div class="projects-item projects-head">
        <div class="model-item-model">Calculator</div>
        <div class="model-item-project">Project</div>
        <div class="model-item-date">Date</div>
    </div>
    <?php
    if( !empty( $calculators ) ):
        foreach( $calculators as $calculator ):

            $calculatorId = $calculator['id'];
            $project      = ( new Project( "getProjectByCalculatorId" ) )->request( $params = array("calculator_id" => $calculatorId ) );
            $projectName  = $project['name'];
            $projectId    = $project['id'];

            ?>
            <div class="projects-item">
                <div class="model-item-model">
                    <div class="projects-item-img"><img src="./images/icons/calculator_icon.png"></div>
                    <div class="projects-item-project"><?= $projectName; ?></div>
                </div>
                <div class="model-item-project"><?= $projectName; ?></div>

                <div class="model-item-date"><?= $calculator['date']." ".$calculator['time']; ?></div>

                <div class="projects-item-control">
                    <div class="projects-item-modelLink">
                        <form action="<?= APPLICATION_HOME; ?>" method="POST">
                            <input type="hidden" class="projectId" name="projectId" value="<?= $projectId; ?>">
                            <input type="hidden" name="path" value="calculators">
                            <input type="hidden" name="attr" value="calculator">
                            <button name="modelProjectSubmit" type="submit" class="button">preview</button>
                        </form>
                    </div>

                    <div class="projects-item-modelLink">
                        <form action="<?= APPLICATION_HOME; ?>" method="POST">
                            <input type="hidden" name="modelId" value="<?= $calculatorId; ?>">
                            <input type="hidden" name="path" value="calculators">
                            <input type="hidden" name="attr" value="validateCalculator">
                            <button name="modelProjectSubmit" type="submit" class="button">validation report</button>
                        </form>
                    </div>

                    <?php if( $calculatorId != $sessionCalculatorId ): ?>
                        <div class="projects-item-modelLink">
                            <form action="<?= APPLICATION_HOME; ?>" method="POST">
                                <input type="hidden" name="calculatorId" value="<?= $calculatorId; ?>">
                                <input type="hidden" name="projectId" value="<?= $projectId; ?>">
                                <input type="hidden" name="changeCheck" value="changeCheck">
                                <input type="hidden" name="path" value="calculators">
                                <input type="hidden" name="attr" value="changeCalculator">
                                <button name="calculatorChangeSubmit" type="submit" class="button">change</button>
                            </form>
                        </div>

                    <?php elseif( $calculatorId == $sessionCalculatorId ): ?>
                        <div class="projects-item-modelLink"><b>Delete this calculator?</b></div>
                        <div class="projects-item-modelLink">
                            <form action="<?= APPLICATION_HOME; ?>" method="POST">
                                <input type="hidden" name="calculatorId" value="<?= $calculatorId; ?>">
                                <input type="hidden" name="projectId" value="<?= $projectId; ?>">
                                <input type="hidden" name="changeCheck" value="accepted">
                                <input type="hidden" name="path" value="calculators">
                                <input type="hidden" name="attr" value="changeCalculator">
                                <button name="calculatorChangeSubmit" type="submit" class="button">yes</button>
                            </form>
                        </div>
                        <div class="projects-item-modelLink">
                            <form action="<?= APPLICATION_HOME; ?>" method="POST">
                                <input type="hidden" name="calculatorId" value="<?= $calculatorId; ?>">
                                <input type="hidden" name="projectId" value="<?= $projectId; ?>">
                                <input type="hidden" name="changeCheck" value="declined">
                                <input type="hidden" name="path" value="calculators">
                                <input type="hidden" name="attr" value="changeCalculator">
                                <button name="calculatorChangeSubmit" type="submit" class="button">no</button>
                            </form>
                        </div>
                    <?php endif; ?>

                </div>
            </div>
            <?php
        endforeach;
    else: ?>
        <div class="projects-message">No calculators available, create a new calculator in the left panel.</div>
    <?php endif;
    ?>
</div>