<div class="login">
    <div class="login-hero">
        <div class="registerTitle"><h1>Register</h1></div>
        <form action="<?= APPLICATION_HOME; ?>" method="post">
            <input type="email" name="email" value="" title="Enter your email address" placeholder="Email address">
            <br>
            <input type="password" name="password" value="" title="Enter your password" placeholder="Password">
            <br>
            <input type="password" name="passwordRepeat" value="" title="Repeat your password, please" placeholder="Password repeat">
            <br>
            <input type="hidden" name="path" value="login">
            <input type="hidden" name="attr" value="register">
            <input type="submit" name="registerSubmit" value="Register">
        </form>
    </div>
</div>
