<div class="pageInfo-title">Preview</div>
<p>
    Want to see the calculator in action? Click on the preview button under the calculator name.
</p>
<div class="pageInfo-title">Validation Report</div>
<p>
    The validation report is always available under each uploaded calculator.
</p>
<div class="pageInfo-title">Change</div>
<p>
    Calculator change only applies to validation mode and test mode.
    <br>
    A calculator is sealed to the project when in accepting or production mode.
    <br><br>
    Want to know more about project modes? Go to the <a href="">Blueberry Database</a>
</p>