<div class="pageInfo-title">Welcome</div>
<?php if( !isset( $_SESSION['menu_toggle'] ) ): ?>
    <div class="pageInfo-dashControl"><a href="<?= APPLICATION_HOME; ?>?hideMenu" class="button">Hide dashboard</a></div>
<?php endif; ?>
<h3>Welcome to Blueberry</h3>
<h5>Blueberry is a middleware service between the model, calculation kernel and the end-user.</h5>
<div class="pageInfo-header">
    <div class="left"><img src="images/icons/middleware.png"></div>
    <div class="right">The process</div>
</div>
<div class="pageInfo-process">
    <div class="pageInfo-process-item">
        <div class="pageInfo-process-item-number">1</div>
        <div class="pageInfo-process-item-img"><img src="images/icons/project_icon.png"></div>
        <div class="pageInfo-process-item-name"><a class="button" href="<?= APPLICATION_HOME; ?>?newProject">Start a new project</a></div>
    </div>
    <div class="pageInfo-process-item">
        <div class="pageInfo-process-item-number">2</div>
        <div class="pageInfo-process-item-img"><img src="images/icons/model_icon.png"></div>
        <div class="pageInfo-process-item-name"><a class="button" href="<?= APPLICATION_HOME; ?>?newModel">Upload a model</a></div>
    </div>
    <div class="pageInfo-process-item">
        <div class="pageInfo-process-item-number">3</div>
        <div class="pageInfo-process-item-img"><img src="images/icons/calculator_icon.png"></div>
        <div class="pageInfo-process-item-name"><a class="button" href="<?= APPLICATION_HOME; ?>?newCalculator">Upload a calculator</a></div>
    </div>
</div>

<div class="pageInfo-title">Information</div>
<p>
    <a class="button" href="<?= APPLICATION_HOME; ?>?blueberryManual">The Blueberry Manual</a> provides detailed documentation about the service.
    <br><br>
    -
</p>
<div class="pageInfo-title">Powered by</div>
<img src="images/icons/quaratio_logo.svg" class="quaratioImage">
