<div class="pageInfo-title">Preview</div>
<p>
    Want to see the model in action? Click on the preview button under the model name.
    <br><br>
    Preview is only available when a model passes validation.
</p>
<div class="pageInfo-title">Validation Report</div>
<p>
    The validation report is available under each uploaded model.
    <br>
    Models can be changed to re-validate, go to models and click change under the model.
</p>
<div class="pageInfo-title">Supported</div>
<p>
    <img src="images/icons/xml_file_icon.png" class="xmlImage">
    <img src="images/icons/ea_logo.gif" class="eaImage">
</p>
<div class="pageInfo-title">Powered by</div>
<p>
    <img src="images/icons/quaratio_logo.svg" class="quaratioImage">
</p>