<div class="pageInfo-title">Validation Report</div>
<p>
    The validation report is available after uploading a model, click on "validation report" to review a report.
    <br><br>
    Models can be changed to re-validate, click "change" to upload a new or improved model.
</p>

<div class="pageInfo-title">Preview</div>
<p>
   The preview of the model is only available when the model has passed validation successful.
    <br><br>
    Without a calculator the entered data will not be stored and operations on the calculation kernel will no be executed.
</p>

<div class="pageInfo-title">Supported</div>
<p>
    <img src="images/icons/xml_file_icon.png" class="xmlImage">
    <img src="images/icons/ea_logo.gif" class="eaImage">
</p>


<div class="pageInfo-title">Powered by</div>
<img src="images/icons/quaratio_logo.svg" class="quaratioImage">