<div class="pageInfo-title">Preview</div>
<p>
    Want to see the model in action? Click on the preview button under the model name.
</p>
<div class="pageInfo-title">Validation Report</div>
<p>
    The validation report is always available under each uploaded model.
</p>
<div class="pageInfo-title">Change</div>
<p>
    Model change only applies to validation mode and test mode.
    <br><br>
    <b>Validation:</b>
    <br>
    The model will be deleted automatically and a new model can be uploaded.
    <br><br>
    <b>Testing:</b>
    <br>
    The model can only be deleted manually.
    <br><br>
    <b>Accepting and production:</b>
    <br>
    A model is sealed to the project when in accepting or production mode.
    <br><br>
    Want to know more about project modes? Go to the <a href="">Blueberry Database</a>
</p>