<div class="pageInfo">
    <div class="pageInfo-title">New calculator</div>
    <p>
        Upload an excel file which contains the calculator.
        <br>
        After the upload, the calculator file will be validated and a report will be displayed.
        <br><br>
        <b>Note:</b>
        <br><br>
        - Existing calculators will be validated but not stored.
        <br>
        - There are restrictions on the calculator structure, you can review them <a href="">here</a>.
        <br>
        - Go to calculators if you want to replace or delete an uploaded calculator file.
    </p>
    <div class="pageInfo-title">Powered by</div>
    <p>
        <img src="images/icons/quaratio_logo.svg" class="quaratioImage">
    </p>
</div>