<div class="pageInfo">
    <div class="pageInfo-title">New model</div>
    <p>
        Upload an xml file which contains the model.
        <br>
        After the upload, the xml file will be validated and a report will be displayed.
        <br><br>
        <b>Note:</b>
        <br><br>
         - Existing xml models will be validated but not stored.
        <br>
        - There are restrictions on the model structure, you can review them <a href="">here</a>.
        <br>
         - Go to models if you want to replace or delete an uploaded xml file.
    </p>
</div>
<div class="pageInfo-title">Powered by</div>
<p>
    <img src="images/icons/quaratio_logo.png" class="quaratioImage">
</p>