<div class="pageInfo-title">Information</div>
<p>
    <strong>Name and description</strong>
    <br><br>
    Requirements:
    <br>
    - No special characters i.e. ;<>''?(){}[]\/|
    <br>
    - Short and descriptive.
    <br>
    - Projects can not have the same name.
    <br><br>
    <strong>Public and private</strong>
    <br><br>
    Public projects can be viewed by all members of this organization.
    <br>
    Private projects can only be viewed by you or a supervisor.
    <br><br>
    If you wish to share your project or one of it's core elements you can do so at the project settings.
    <br><br>
    <strong>Model, calculator and documents can be uploaded immediately after creation.</strong>
</p>
<div class="pageInfo-title">Powered by</div>
<img src="images/icons/quaratio_logo.svg" class="quaratioImage">
