<div class="pageInfo-title">New project</div>
<p>
    Enter a name and description to start a new project.
    <br><br>
    Each project consists of the following components:
    <br><br>
    - A model, exported to XML.
    <br>
    - A calculator, responsible for the model calculations.
</p>
<div class="pageInfo-title">Powered by</div>
<p>
    <img src="images/icons/quaratio_logo.svg" class="quaratioImage">
</p>