<div class="pageInfo-title">Model and calculator</div>
<p>
    A model or calculator can be uploaded with the buttons under a project.
    <br><br>
    When a model or calculator is uploaded, a preview button will appear.
    <br><br>
    More model or calculator actions can be found under Models or Calculators.
</p>
<div class="pageInfo-title">Edit or delete a project</div>
<p>
    Projects can be edited or deleted when in validation or testing mode.
</p>
<div class="pageInfo-title">Powered by</div>
<p>
    <img src="images/icons/quaratio_logo.png" class="quaratioImage">
</p>