<div class="pageInfo-title">Projects</div>
<p>
    A project contains a model and a calculator.
    <br>
    Projects have different modes that represent their current state.
    <br><br>
    <strong>Modes:</strong>
    <br><br>
    <u>Validation:</u> The model and calculator can be uploaded and changed during this state. Version control is disabled.
    <br><br>
    <u>Testing:</u> A new version will be added to the project if the model and calculator are changed during this state. Version control enabled.
    <br><br>
    <u>Acceptation:</u> Final checks are done and the project will be sealed afterwards. Version control enabled.
    <br><br>
    <u>Production:</u> The projects is live and can not be edited or deleted. Version control sealed.
</p>
<div class="pageInfo-title">Powered by</div>
<img src="images/icons/quaratio_logo.svg" class="quaratioImage">