<div class="pageInfo-title">Information</div>
<p>
    <strong>Core elements</strong>
    <br>
    A project consists of the following core elements:
    <br><br>
    <span>Uml Class Model</span>
    <span>Excel Calculator</span>
    <span>Database</span>
    <span>Documents</span>
    <br><br>
    <strong>Version control</strong>
    <br>
    Version control starts at testing, after validation.
    <br>
    A new version will be applied each time a new model or calculator is uploaded.
    <br><br>
    The model, calculator and database have version control.
    <br><br>
    <strong>Status and version numbers</strong>
    <br>
    Testing: 00.1
    <br>
    Configuration: 0.1
    <br>
    Production: 1
    <br><br>
    <strong>Configuration</strong>
    <br>
    The configuration will lock the core elements of a project so it maintains it reproducibility.
    <br><br>
    <strong>Locked project</strong>
    <br>
    Locked projects can not be edited or deleted.



</p>
<div class="pageInfo-title">Powered by</div>
<img src="images/icons/quaratio_logo.svg" class="quaratioImage">