<menu>
    <nav>
        <ul>
            <li><a href="<?= APPLICATION_HOME; ?>" class="button">Home</a></li>
            <li><a href="<?= APPLICATION_HOME; ?>?projects" class="button">Projects</a></li>
            <li><a href="<?= APPLICATION_HOME; ?>?models" class="button">Models</a></li>
            <li><a href="<?= APPLICATION_HOME; ?>?calculators" class="button">Calculators</a></li>
        </ul>
    </nav>

    <?php if( isset( $_GET ) && !empty( $_GET ) ): ?>
        <div class="pageMenu">
        <?php switch( $_GET ):
            case (isset($_GET['projects'])
                || isset($_GET['newProject'])
                || isset($_GET['newProjectEmptyFields'])
                || isset($_GET['projectExists'])
                || isset($_GET['deleteProjectAccept'])):
                require_once "web/pageMenus/projects.phtml";
                break;
            case (isset($_GET['models'])
                || isset($_GET['modelUploadNoFile'])
                || isset($_GET['newModel'])
                || isset($_GET['xmlEAValidatorReport'])
                || isset($_GET['model'])
                || isset($_GET['changeModelAccept'])
                || isset($_GET['modelUploadNoProject'])):
                require_once "web/pageMenus/models.phtml";
                break;
            case (isset($_GET['newCalculator'])
                || isset($_GET['calculators'])
                || isset($_GET['calculatorUploadNoFile'])
                || isset($_GET['calculatorUploadInvalidFileExtension'])
                || isset($_GET['changeCalculatorAccept'])
                || isset($_GET['calculatorUploadNoProject'])
                || isset($_GET['calculatorExists'])):
                require_once "web/pageMenus/calculators.phtml";
                break;
        endswitch; ?>
        </div>
        <div class="pageInfo">
            <?php switch( $_GET ):
                case (isset( $_GET['newProject'] )
                    || isset($_GET['newProjectEmptyFields'])
                    || isset($_GET['projectExists'])
                    || isset($_GET['modelUploadNoProject'])):
                    require_once "web/pageInfo/newProject.phtml";
                    break;
                case (isset( $_GET['projects'] )
                    || isset($_GET['deleteProjectAccept'])):
                    require_once "web/pageInfo/projects.phtml";
                    break;
                case (isset($_GET['newModel'])
                    || isset($_GET['modelUploadNoFile'])):
                    require_once "web/pageInfo/newModel.phtml";
                    break;
                case (isset( $_GET['xmlEAValidatorReport'] )):
                    require_once "web/pageInfo/validatorReport.phtml";
                    break;
                case (isset( $_GET['models'] )
                    || isset( $_GET['changeModelAccept'] )):
                    require_once "web/pageInfo/models.phtml";
                    break;
                case (isset( $_GET['model'] )):
                    require_once "web/pageInfo/model.phtml";
                    break;
                case (isset($_GET['newCalculator'])
                    || isset($_GET['calculatorUploadInvalidFileExtension'])
                    || isset($_GET['calculatorUploadNoFile'])
                    || isset($_GET['calculatorUploadNoProject'])
                    || isset($_GET['calculatorExists'])):
                    require_once "web/pageInfo/newCalculator.phtml";
                    break;
                case (isset($_GET['calculators'])
                    || isset($_GET['changeCalculatorAccept'])):
                    require_once "web/pageInfo/calculators.phtml";
                    break;
            endswitch; ?>
        </div>
    <?php endif; ?>

</menu>
<div class="border"></div>
