<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="keywords" content="">
        <meta name="robots" content="nofollow">
        <meta property="og:title" content="Control Management System">
        <meta property="og:type" content="website">
        <meta property="og:description" content="">
        <meta property="og:url" content="">
        <meta property="og:image" content="">
        <link href="https://fonts.googleapis.com/css?family=Raleway%7cPassion+One%7cWork+Sans%7cRoboto+Condensed:400" rel="stylesheet" type="text/css">
        <link rel="stylesheet" type="text/css" href="css/style.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <title>QuaRatio</title>
    </head>
    <body>

        <?php

        use app\lib\Login;
        use app\lib\ViewController;

        if( isset( $_GET['hideMenu'] ) ):
            $_SESSION['menu_toggle'] = "hide";
            ?> <script>window.history.back()</script><?php
        elseif( isset( $_GET['showMenu'] ) ):
        unset($_SESSION['menu_toggle']);
        ?> <script>window.history.back()</script><?php
        endif;

        /**
         * Header
         */
        ( new ViewController( "header", "common" ) )->request();

        /**
        * Login check
        */
        $login = ( new Login( "isLoggedIn" ) )->request( $params = null );

        if( $login === false ):
            ( new ViewController( "login", "login" ) )->request();
        else: ?>
        <div id="main">
            <?php
            /**
             * Menu
             */
            if( !isset( $_GET['register'] ) ):
                ( new ViewController( "dashboard", "common" ) )->request();
            endif;
            /**
             * Main content
             */
            ?>
            <div id="application">
                <?php
                    if( !empty( $_GET ) ):
                        ( new ViewController( "", "" ) )->getRequest( $_GET );
                    else:
                        ( new ViewController( "home", "common" ) )->request();
                    endif;
                ?>
            </div>
        </div>

            <?php
        endif;

        /**
         * Footer
         */
        ( new ViewController( "footer", "common" ) )->request();
        ?>

    </body>
</html>