<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="keywords" content="">
        <meta name="robots" content="nofollow">
        <meta property="og:title" content="Control Management System">
        <meta property="og:type" content="website">
        <meta property="og:description" content="">
        <meta property="og:url" content="">
        <meta property="og:image" content="">
        <link href="https://fonts.googleapis.com/css?family=Raleway%7cPassion+One%7cWork+Sans%7cRoboto+Condensed:400" rel="stylesheet" type="text/css">
        <link rel="stylesheet" type="text/css" href="css/style.css">
        <title>QuaRatio</title>
    </head>
    <body>

        <?php

        use app\lib\Login;
        use app\lib\ViewController;

        /**
         * Header
         */
        ( new ViewController( "header", "common" ) )->request();

        /**
        * Login check
        */
        $login = ( new Login( "", "" ) )->isLoggedIn();

        if( $login === false ):
            ( new ViewController( "login", "login" ) )->request();
        else: ?>
        <div id="main">
            <?php
            /**
             * Menu
             */
                ( new ViewController( "dashboard", "common" ) )->request();

            /**
             * Main content
             */
            ?>
            <div id="application">
                <?php
                    if( !empty( $_GET ) ):
                        ( new ViewController( "", "" ) )->getRequest( $_GET );
                    else:
                        ( new ViewController( "home", "common" ) )->request();
                    endif;
                ?>
            </div>
        </div>

            <?php

        endif;

        /**
         * Footer
         */
        ( new ViewController( "footer", "common" ) )->request();
        ?>

    </body>
</html>