<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="keywords" content="">
        <meta name="robots" content="nofollow">
        <meta property="og:title" content="Control Management System">
        <meta property="og:type" content="website">
        <meta property="og:description" content="">
        <meta property="og:url" content="">
        <meta property="og:image" content="">
        <link href="https://fonts.googleapis.com/css?family=Raleway%7cPassion+One%7cWork+Sans%7cRoboto+Condensed:400" rel="stylesheet" type="text/css">
        <link rel="stylesheet" type="text/css" href="css/style.css">
        <title>QuaRatio</title>
    </head>
    <body>

        <?php

        use app\core\Login;
        use app\lib\ViewController;

        /**
        * Login
        */
        $login = ( new Login( "", "" ) )->isLoggedIn();

        if( !$login ):

            ( new ViewController( "login", "login" ) )->request();

        /**
         * Main content
         */
        else: ( new ViewController( "header", "common" ) )->request(); ?>

        <div id="main">
            <?php ( new ViewController( "home", "common" ) )->request(); ?>
        </div>

        <?php

        endif;

        /**
         * Footer
         */
        ( new ViewController( "footer", "common" ) )->request();
        ?>

    </body>
</html>