<?php
/**
 * Created by PhpStorm.
 * User: Ruben Hazenbosch
 * Date: 01-Aug-16
 * Time: 19:22
 */

?>

<footer>
    <div class="footer-copy">
        &copy; Copyright 2016 QuaRatio B.V.
    </div>
    <div class="footer-info">
        Powered by QuaRatio
        <br>
        Blueberry ProductSuite
    </div>
</footer>
<?php
    if( isset( $_GET['new'] )
        || isset( $_GET['edited'] )
        || isset( $_GET['deleted'] )
        || isset( $_GET['modelUploaded'] )): ?>
    <div class="projects-message">
        <span>
            <?php
            switch( $_GET ):
                case( isset( $_GET['new'] ) ):
                    echo "New project has been created.";
                    break;
                case( isset( $_GET['modelUploaded'] ) ):
                    echo "Model upload successful, report is generated.";
                    break;
                case( isset( $_GET['edited'] ) ):
                    echo "Project is edited.";
                    break;
                case( isset( $_GET['deleted'] ) ):
                    echo "Project is deleted.";
                    break;
            endswitch;
            ?>
        </span>
    </div>
    <script>
        $(document).ready(function(){
            $(".projects-message").delay(4000).animate({ height: 0, opacity: 0 }, 'fast');
        });
    </script>
<?php endif;
