<header>
    <div class="title">Blueberry
        <?php if( isset( $_SESSION['userId'] ) ): ?>
            <?php if( isset( $_SESSION['menu_toggle'] ) ): ?>
                <a href=" <?= APPLICATION_HOME; ?>?showMenu" class="button">Show dashboard</a>
            <?php else: ?>
                <a href="<?= APPLICATION_HOME; ?>?hideMenu" class="button">Hide dashboard</a>
            <?php endif; ?>
        <?php endif; ?>
    </div>
    <?php if( isset( $_SESSION['userId'] ) ): ?>
    <menu>
    <nav>
        <ul>
            <li><a href="<?= APPLICATION_HOME; ?>" class="button">Home</a></li>
            <li><a href="<?= APPLICATION_HOME; ?>?projects" class="button">Projects</a></li>
            <li><a href="<?= APPLICATION_HOME; ?>?models" class="button">Models</a></li>
            <li><a href="<?= APPLICATION_HOME; ?>?calculators" class="button">Calculators</a></li>
            <li><a href="<?= APPLICATION_HOME; ?>?calculators" class="button">Blueberry manual</a></li>
        </ul>
    </nav>
    </menu>
    <?php endif; ?>
    <?php
        if( isset( $_SESSION['userId'] ) ): ?>
        <a href="<?= APPLICATION_LOGOUT; ?>" class="button">Logout</a>
        <?php if( $_SESSION['userId'] === 22 ): ?>
            <a href="<?= APPLICATION_REGISTER; ?>" class="button">Register</a>
        <?php endif; ?>
    <?php endif; ?>
</header>
