<?php

use app\lib\Login;
use app\lib\Project;
use app\lib\Models;
use app\lib\Calculator;

/**
 * Collect all data for overview
 */
$getUserLastLogin          = ( new Login( "getPreviousLogin" ) )->request( $params = null );
$getTotalProjects          = ( new Project( "countProjects" ) )->request( $params = null );
$getTotalProjectsByUser    = ( new Project( "getAllProjectsByUser" ) )->request( $params = null );
$getTotalModels            = ( new Models( "countModels" ) )->request( $params = null );
$getTotalModelsByUser      = ( new Models( "getAllModelsByUser" ) )->request( $params = null );
$getTotalCalculators       = ( new Calculator( "countCalculators" ) )->request( $params = null );
$getTotalCalculatorsByUser = ( new Calculator( "getAllCalculatorsByUser" ) )->request( $params = null );

/**
 * Check the collected data and set appropriate.
 */
$userLastLogin          = ( !empty( $getUserLastLogin ) ? $getUserLastLogin : "" );
$totalProjects          = ( !empty( $getTotalProjects ) ? $getTotalProjects : 0 );
$totalProjectsByUser    = ( !empty( $getTotalProjectsByUser ) ? count( $getTotalProjectsByUser ) : 0 );
$totalModels            = ( !empty( $getTotalModels ) ? $getTotalModels : 0 );
$totalModelsByUser      = ( !empty( $getTotalModelsByUser ) ? count( (array) $getTotalModelsByUser ) : 0 );
$totalCalculators       = ( !empty( $getTotalCalculators ) ? $getTotalCalculators : 0 );
$totalCalculatorsByUser = ( !empty( $getTotalCalculatorsByUser ) ? count( $getTotalCalculatorsByUser ) : 0 );
?>

<div class="home">
    <div class="home-hero">
            <div class="home-hero-overview">
                <h2>Welcome to Blueberry
                    <?php if( !empty( $userLastLogin ) ): ?>
                        <small>Your last visit was on: <?= date( "d-m-Y H:i:s", strtotime( $userLastLogin ) ); ?></small>
                    <?php endif; ?>
                </h2>
                <h4>Middleware for math and data financiers</h4>
                <table>

                    <tr>
                        <td>Total projects</td>
                        <td><?= $totalProjects; ?></td>
                     </tr>
                    <tr>
                        <td>Total models</td>
                        <td><?= $totalModels; ?></td>
                    </tr>
                    <tr>
                        <td>Total Calculators</td>
                        <td><?= $totalCalculators; ?></td>
                    </tr>

                    <tr><td><hr></td></tr>

                    <tr>
                        <td>My total projects</td>
                        <td><?= $totalProjectsByUser; ?></td>
                    </tr>
                    <tr>
                        <td>My total models</td>
                        <td><?= $totalModelsByUser; ?></td>
                    </tr>
                    <tr>
                        <td>My total calculators</td>
                        <td><?= $totalCalculatorsByUser; ?></td>
                    </tr>
                </table>
            </div>
    </div>
</div>