<?php
/**
 * Created by PhpStorm.
 * User: Ruben Hazenbosch
 * Date: 12-Sep-16
 * Time: 10:34
 */

use app\lib\ProjectDocuments;

$projectId        = ( !empty( $_GET['projectDocuments'] ) ? $_GET['projectDocuments'] : "" );
$params           = array("project_id" => $projectId);
$documents        = ( new ProjectDocuments( "getDocuments" ) )->request( $params );
$documents_groups = ( new ProjectDocuments( "getDocumentsGroups" ) )->request( $params );

?>
<div class="newDocument">
    <div class="modelReport-Title">Project Document Upload <?= ( !empty( $projectName ) ? "for " . $projectName : "" ) ?></div>

    <form action="<?= APPLICATION_HOME; ?>" method="post" enctype="multipart/form-data">
            <input type="hidden" name="projectId" value="<?= $projectId; ?>">
            <input type="hidden" name="path" value="projects">
            <input type="hidden" name="attr" value="documents">

            <input type="text" name="name" value="" placeholder="Document name">
            <input type="text" name="groupName" value="" placeholder="Document group">

            <?php
                if( !empty( $documents_groups ) ):
                    ?>
                    <br>
                    <select name="group">
                        <option name="" value="">Select a group</option>
                    <?php
                    foreach( $documents_groups as $documents_group ):
                        echo '<option name="documentGroup" value="' . $documents_group['group_name'] . '">' . $documents_group['group_name'] . '</option>';
                    endforeach;
                    ?>
                    </select><br>
                    <?php
                endif;
            ?>
            <br>
            <input type="file" name="document" id="document" value="" title="Kies een bestand.">
            <input type="submit" name="projectDocumentUploadSubmit" value="Uploaden" title="Upload a document.">
    </form>
</div>
<?php
if( !empty( $documents_groups ) ):
    foreach( $documents_groups as $documents_group ):
        var_dump( $documents_group );
    endforeach;
endif;
?>