<?php
/**
 * Created by PhpStorm.
 * User: Ruben Hazenbosch
 * Date: 2-8-2016
 * Time: 16:29
 */

?>

<div class="login">
    <div class="title">New project</div>
    <form action="<?= APPLICATION_HOME; ?>" method="post">
        <input type="text" name="name" value="" title="Enter a name" placeholder="Name">
        <input type="text" name="description" value="" title="Enter a description" placeholder="Description">
        <input type="hidden" name="path" value="projects">
        <input type="hidden" name="attr" value="newProject">
        <input type="submit" name="newProjectSubmit" value="Create project">
    </form>

    <?php if( isset( $_GET['newProjectEmptyFields'] ) ): ?>
        <div class="projects-message-title">There are empty fields.</div>
    <?php endif; ?>
    <?php if( isset( $_GET['projectExists'] ) ): ?>
        <div class="projects-message-title">The project name is already in use.</div>
    <?php endif; ?>
</div>
