<?php
/**
 * Created by PhpStorm.
 * User: Ruben Hazenbosch
 * Date: 2-8-2016
 * Time: 16:29
 */

?>

<div class="newProject">
    <div class="modelReport-Title">New project</div>
    <form action="<?= APPLICATION_HOME; ?>" method="post">
        <input type="hidden" name="path" value="projects">
        <input type="hidden" name="attr" value="newProject">

        <input type="text" name="name" value="" title="Enter a name" placeholder="Name">
        <input type="text" name="description" value="" title="Enter a description" placeholder="Description">
        <div class="newProject-type">
            <label><input type="radio" name="type" value="public" checked="checked">Public</label>
            <label><input type="radio" name="type" value="private">Private</label>
        </div>
        <input type="submit" name="newProjectSubmit" value="Create project" class="button">
    </form>

    <?php if( isset( $_GET['newProjectEmptyFields'] ) ): ?>
        <div class="projects-message-title">There are empty fields.</div>
    <?php endif; ?>
    <?php if( isset( $_GET['projectExists'] ) ): ?>
        <div class="projects-message-title">The project name is already in use.</div>
    <?php endif; ?>
</div>
