<?php
/**
 * Created by PhpStorm.
 * User: Ruben Hazenbosch
 * Date: 01-Aug-16
 * Time: 22:54
 */

use app\lib\Project;
use app\enterpriseArchitecture\IOXMLEAModel;

$projects               = ( new Project( "getAllProjects" ) )->request( $params = null );
$projectsByUser         = ( new Project( "getAllProjectsByUser" ) )->request( $params = null );
$newProject             = ( !empty( $_GET['project'] ) ? $_GET['project'] : "" );
$lastAddedProject       = ( new Project( "getLastAddedProject" ) )->request( $params = null );
$lastAddedProjectByUser = ( new Project( "getLastAddedProjectByUser" ) )->request( $params = null );

unset($_SESSION['xmlModelId']);

$userProjectIds = array();
if( !empty( $projectsByUser ) ):
    foreach( $projectsByUser as $projectByUser ):
        $userProjectIds[] = $projectByUser['id'];
    endforeach;
endif;

?>

<div class="projects">

    <div class="projects-item projects-head">
        <div class="projects-item-name head">Project</div>
        <div class="projects-item-model head">Model</div>
        <div class="projects-item-calculator head">Calculator</div>
        <div class="projects-item-descr head">Status</div>
        <div class="projects-item-date head">Created</div>
        <div class="projects-item-info head">Info</div>
    </div>

    <?php
        if( !empty( $projects ) ):
            foreach( $projects as $project ):

            $params       = array( "project_id" => $project['id'] );
            $modelData    = ( new Project( "getModelIdByProjectId" ) )->request( $params );
            $projectId    = ( isset( $project['id'] ) ? $project['id'] : "" );
            $projectName  = ( isset( $project['name'] ) ? $project['name'] : "" );
            $calculator   = ( new Project( "getCalculatorIdByProjectId" ) )->request( $params );
            $calculatorId =  ( !empty( $calculator['calculator_id'] ) ? $calculator['calculator_id'] : "" );

            if( !empty( $modelData ) ):
                $hasModel   = true;
                $modelId    = $modelData['model_id'];
                $model      = ( new IOXMLEAModel( $modelId ) )->getModel();
            else:
                $hasModel = false;
                $modelId  = "";
            endif;

            ?>
            <div class="projects-item">

                <div class="projects-item-name">
                    <div class="projects-item-img"><img src="./images/icons/project_icon.png"></div>
                    <div class="projects-item-project"><?= $projectName; ?></div>
                </div>
                <div class="projects-item-model"><?= ( $hasModel === true ? "yes" : "no" ); ?></div>
                <div class="projects-item-calculator"><?= ( !empty( $calculatorId ) ? "yes" : "no" ); ?></div>
                <div class="projects-item-descr"><?= $project['status']; ?></div>
                <div class="projects-item-date"><?= $project['date']." ".$project['time']; ?></div>
                <div class="projects-item-info">
                    <?= ( in_array( $projectId, $userProjectIds ) ? "<div class=\"projects-item-myNew\">my project</div>" : "" ); ?>
                    <?= ( !empty( $lastAddedProject ) && $lastAddedProject == $projectId ? " <div class=\"projects-item-newest\">new</div>" : "" ); ?>
                </div>

                <div class="projects-item-control">

                    <?php if( $hasModel === false ): $modelValue = "model upload"; else: $modelValue = "model preview"; endif; ?>
                    <div class="projects-item-modelLink">
                        <form action="<?= APPLICATION_HOME; ?>" method="POST">
                            <input type="hidden" name="projectId" value="<?= $projectId; ?>">
                            <input type="hidden" name="path" value="models">
                            <input type="hidden" name="attr" value="model">
                            <input type="submit" name="modelProjectSubmit" class="button" value="<?= $modelValue; ?>">
                        </form>
                    </div>

                    <?php if( empty( $calculatorId ) ): $calculatorValue = "calculator upload"; else: $calculatorValue = "calculator preview"; endif; ?>
                    <div class="projects-item-modelLink">
                        <form action="<?= APPLICATION_HOME; ?>" method="POST">
                            <input type="hidden" name="projectId" value="<?= $projectId; ?>">
                            <input type="hidden" name="path" value="calculators">
                            <input type="hidden" name="attr" value="calculator">
                            <input type="submit" name="calculatorProjectSubmit" class="button" value="<?= $calculatorValue; ?>">
                        </form>
                    </div>

                    <div class="projects-item-modelLink">
                        <a href="<?= APPLICATION_HOME; ?>?projectDocuments=<?= $projectId ?>" class="button">Documents</a>
                    </div>

                    <div class="projects-item-modelLink">
                        <form action="<?= APPLICATION_HOME; ?>" method="POST">
                            <input type="hidden" name="projectId" value="<?= $projectId; ?>">
                            <input type="hidden" name="path" value="projects">
                            <input type="hidden" name="attr" value="settings">
                            <input type="submit" name="projectSettingsSubmit" class="button" value="Settings">
                        </form>
                    </div>



                    <?php if( $hasModel === false && empty( $calculatorId ) ): ?>
                        <div class="project-itemNoModel">This project has no model and no calculator</div>
                    <?php elseif( $hasModel === false ): ?>
                        <div class="project-itemNoModel">This project has no model</div>
                    <?php elseif( empty( $calculatorId ) ): ?>
                        <div class="project-itemNoModel">This project has no calculator</div>
                    <?php endif; ?>
                </div>
            </div>

            <?php endforeach;
        else: ?>
            <div class="projects-message-title">No projects available, create a new project in the left panel.</div>
        <?php endif; ?>
</div>


