<?php
/**
 * Created by PhpStorm.
 * User: Ruben Hazenbosch
 * Date: 01-Aug-16
 * Time: 22:54
 */

use app\lib\Project;
use app\enterpriseArchitecture\IOXMLEAModel;

$projects = ( new Project( "getAllProjectsByUser" ) )->request( $params = null );

?>

<div class="projects">

    <div class="projects-item projects-head">
        <div class="projects-item-name">Project</div>
        <div class="projects-item-descr">Status</div>
        <div class="projects-item-date">Date</div>
        <div class="projects-item-model">Model</div>
        <div class="projects-item-calculator">Calculator</div>
        <div class="projects-item-active">Active</div>
    </div>

    <?php
        if( !empty( $projects ) ):
            foreach( $projects as $project ):

            $params       = array( "project_id" => $project['id'] );
            $modelData    = ( new Project( "getModelIdByProjectId" ) )->request( $params );
            $calculator   = ( new Project( "getCalculatorIdByProjectId" ) )->request( $params );
            $calculatorId =  ( !empty( $calculator['calculator_id'] ) ? $calculator['calculator_id'] : "" );

            if( !empty( $modelData ) ):
                $hasModel   = true;
                $modelId    = $modelData['model_id'];
                $model      = ( new IOXMLEAModel( $modelId ) )->getModel();
            else:
                $hasModel = false;
            endif;

            ?>
            <div class="projects-item">
                <div class="projects-item-name">
                    <div class="projects-item-img"><img src="./images/icons/project_icon.png"></div>
                    <div class="projects-item-project"><?= $project['name']; ?></div>
                </div>
                <div class="projects-item-descr"><?= $project['status']; ?></div>
                <div class="projects-item-date"><?= $project['date']." ".$project['time']; ?></div>
                <div class="projects-item-model"><?= ( $hasModel === true ? "yes" : "no" ); ?></div>
                <div class="projects-item-calculator"><?= ( !empty( $calculatorId ) ? "yes" : "no" ); ?></div>
                <div class="projects-item-active">no</div>

                <div class="projects-item-control">
                    <?php if( $hasModel === false ): $modelValue = "model upload"; else: $modelValue = "model preview"; endif; ?>
                    <div class="projects-item-modelLink">
                        <form action="<?= APPLICATION_HOME; ?>" method="POST">
                            <input type="hidden" class="projectId" name="projectId" value="<?= $project['id']; ?>">
                            <input type="hidden" name="path" value="models">
                            <input type="hidden" name="attr" value="model">
                            <input type="submit" name="modelProjectSubmit" class="button" value="<?= $modelValue; ?>">
                        </form>
                    </div>
                    <?php if( empty( $calculatorId ) ): $calculatorValue = "calculator upload"; else: $calculatorValue = "calculator preview"; endif; ?>
                    <div class="projects-item-modelLink">
                        <form action="<?= APPLICATION_HOME; ?>" method="POST">
                            <input type="hidden" class="projectId" name="projectId" value="<?= $project['id']; ?>">
                            <input type="hidden" name="path" value="calculators">
                            <input type="hidden" name="attr" value="calculator">
                            <input type="submit" name="calculatorProjectSubmit" class="button" value="<?= $calculatorValue; ?>">
                        </form>
                    </div>
                    <div class="projects-item-modelLink"><a href="" class="button">edit project</a></div>
                    <div class="projects-item-modelLink">
                        <form action="<?= APPLICATION_HOME; ?>" method="POST">
                            <input type="hidden" class="projectId" name="projectId" value="<?= $project['id']; ?>">
                            <input type="hidden" name="path" value="projects">
                            <input type="hidden" name="attr" value="delProject">
                            <input type="submit" name="delProjectSubmit" class="button" value="delete project">
                        </form>
                    </div>
                    <?php if( $hasModel === false && empty( $calculator ) ): ?>
                        <div class="project-itemNoModel">This project has no model and no calculator</div>
                    <?php elseif( $hasModel === false ): ?>
                        <div class="project-itemNoModel">This project has no model</div>
                    <?php elseif( empty( $calculator ) ): ?>
                        <div class="project-itemNoModel">This project has no calculator</div>
                    <?php endif; ?>
                </div>
            </div>

            <?php endforeach;
        else: ?>
            <div class="projects-message">No projects available, create a new project in the left panel.</div>
        <?php endif; ?>

</div>

