<?php
/**
 * Created by PhpStorm.
 * User: Ruben Hazenbosch
 * Date: 01-Aug-16
 * Time: 18:46
 */

?>

<div class="login">

    <form action="" method="POST" id="login">
        <input type="email" name="email" value="" title="Enter your email address." placeholder="Email address">
        <input type="password" name="password" value="" title="Enter your password." placeholder="Password">
        <input type="submit" name="loginSubmit" value="Login">
    </form>

</div>

