<?php
/**
 * Created by PhpStorm.
 * User: Ruben Hazenbosch
 * Date: 03-Aug-16
 * Time: 20:57
 */

use app\lib\Project;
use app\enterpriseArchitecture\IOXMLEAScreenFactory;

$modelId         = ( isset( $_SESSION['xmlModelId'] ) ? $_SESSION['xmlModelId'] : "" );
$params          = array( "model_id" => $modelId );
$project         = ( new Project( "getProjectByModelId" ) )->request( $params );
$projectName     = ( isset( $project['name'] ) ? $project['name'] : "" );
$orderedElements = ( new IOXMLEAScreenFactory( "extractAndOrderElements", $modelId ) )->request( $params = null );
$totalElements   = count( $orderedElements );
$currentPage     = ( isset( $_GET['page'] ) ? $_GET['page'] : '1' );
$highestOrder    = $orderedElements['highest_order'];

$_SESSION['project'] = ( !empty( $projectName ) ? $projectName : "" );
$params['elements']  = $orderedElements;
?>
    <div class="newModel-head">
    <div class="title">Model Preview <?= ( !empty( $projectName ) ? "for " . $projectName : "" ) ?></div>
    </div>
<?php
if( !empty( $orderedElements ) ):
    if( $currentPage <= $highestOrder ):
        for( $i = 0; $i < $totalElements; $i++ ):
            if( !empty( $orderedElements[$i] ) ):
                /**
                 * Only print element if there is a print order, if the print order is a digit and if the print order equals the current page.
                 */
                $printOrder = ( isset( $orderedElements[$i]['printOrder'] ) ? $orderedElements[$i]['printOrder'] : "" );
                if( $orderedElements[$i]['printOrder'] !== "noPrint" && ctype_digit( $orderedElements[$i]['printOrder'] ) && $printOrder === $currentPage ):
                    $elementNameBefore = ( isset( $orderedElements[($i-1)]['name'] ) ?  $orderedElements[($i-1)]['name'] : "" );
                    $_SESSION['elementNameBefore'] = $elementNameBefore;
                    /**
                     * Print root first, always contains the intro element
                     * Each element printed after the root contains a form.
                     */
                    ?>
                    <div class="element-Header">
                        <div class="element-Header-link">
                            <a href="http://www.quaratio.com/wordpress" class="button" title="Go to quaratio.com">www.quaratio.com</a>
                        </div>
                        <div class="element-Header-img">
                            <img src="images/icons/quaratio_logo.svg">
                        </div>
                    </div>
                    <?php
                    $root = ( isset( $orderedElements[$i]['isRoot'] ) ? $orderedElements[$i]['isRoot'] : "" );
                    if( $root === "true" ):
                        print_r( ( new IOXMLEAScreenFactory( "buildElementIntro", $orderedElements[$i] ) )->request( $params ) );
                    else:
                        print_r( ( new IOXMLEAScreenFactory( "buildElement", $orderedElements[$i] ) )->request( $params ) );
                    endif;
                endif;
            endif;
        endfor;
    else:
        header("Location: index.php?projectResults");
        exit();
    endif;
endif;
?>
