<?php
/**
 * Created by PhpStorm.
 * User: Ruben Hazenbosch
 * Date: 03-Aug-16
 * Time: 20:57
 */

use app\lib\Project;
use app\enterpriseArchitecture\IOXMLEAScreenFactory;

$modelId         = ( isset( $_SESSION['xmlModelId'] ) ? $_SESSION['xmlModelId'] : "" );
$params          = array( "model_id" => $modelId );
$project         = ( new Project( "getProjectByModelId" ) )->request( $params );
$projectName     = ( isset( $project['name'] ) ? $project['name'] : "" );
$orderedElements = ( new IOXMLEAScreenFactory( "buildScreenArray", $modelId ) )->request( $params = null );
$totalElements   = count( $orderedElements );
$highestOrder    = ( !empty( $orderedElements['highestOrder']['order'] ) ? $orderedElements['highestOrder']['order'] : "" );
$currentPage     = ( isset( $_GET['page'] ) ? $_GET['page'] : 0 );


?>
    <div class="newModel-head">
    <div class="title">Model Preview <?= ( !empty( $projectName ) ? "for " . $projectName : "" ) ?></div>
    </div>
<?php

echo '<pre>';
print_r($orderedElements);

?>
