<?php
/**
 * Created by PhpStorm.
 * User: Ruben Hazenbosch
 * Date: 03-Aug-16
 * Time: 10:48
 */

use app\lib\Models;
use app\lib\Project;

$models         = ( new Models( "getAllModelsByUser" ) )->request( $params = null );
$sessionModelId = ( isset( $_SESSION['model_id'] ) ? $_SESSION['model_id'] : "" );
$getModelId     = ( isset( $_GET['model_id'] ) ? $_GET['model_id']: "" );

unset($_SESSION['project_id']);
unset($_SESSION['model_id']);

?>
<div class="models">
    <div class="projects-item projects-head">
        <div class="model-item-model">Model</div>
        <div class="model-item-project">Project</div>
        <div class="model-item-valid">Valid</div>
        <div class="model-item-date">Date</div>
    </div>
    <?php
        if( !empty( $models ) ):
            foreach($models as $model):
                $modelId        = ( isset( $model['id'] ) ? $model['id'] : "" );
                $project        = ( new Project( "getProjectByModelId" ) )->request( $params = array("model_id" => $modelId) );
                $projectId      = ( isset( $project['id'] ) ? $project['id'] : "" );
                $projectName    = ( !empty( $project['name'] ) ? $project['name'] : "<span>Name not found</span>" );
                $modelName      = ( !empty( $model['name'] ) ? $model['name'] : "<span>Name not found</span>" );
                ?>
                <?= ( $modelId ==$getModelId ? '<div class="projects-item-selected">' : '<div class="projects-item">' ); ?>
                    <div class="model-item-model">
                        <div class="projects-item-img"><img src="./images/icons/model_icon.png"></div>
                        <div class="projects-item-project"><?= $modelName; ?></div>
                    </div>
                    <div class="model-item-project"><?= $projectName; ?></div>
                    <div class="model-item-valid"><?= $model['valid']; ?></div>
                    <div class="model-item-date"><?= $model['date']." ".$model['time']; ?></div>

                    <div class="projects-item-control">
                        <div class="projects-item-modelLink">
                            <form action="<?= APPLICATION_HOME; ?>" method="POST">
                                <input type="hidden" class="projectId" name="projectId" value="<?= $projectId; ?>">
                                <input type="hidden" name="path" value="models">
                                <input type="hidden" name="attr" value="model">
                                <button name="modelProjectSubmit" type="submit" class="button">preview</button>
                            </form>
                        </div>

                        <div class="projects-item-modelLink">
                            <form action="<?= APPLICATION_HOME; ?>" method="POST">
                                <input type="hidden" name="modelId" value="<?= $modelId; ?>">
                                <input type="hidden" name="path" value="models">
                                <input type="hidden" name="attr" value="validateModel">
                                <button name="modelProjectSubmit" type="submit" class="button">validation report</button>
                            </form>
                        </div>

                        <?php if( $modelId != $sessionModelId ): ?>
                        <div class="projects-item-modelLink">
                            <form action="<?= APPLICATION_HOME; ?>" method="POST">
                                <input type="hidden" name="modelId" value="<?= $modelId; ?>">
                                <input type="hidden" name="projectId" value="<?= $projectId; ?>">
                                <input type="hidden" name="changeCheck" value="changeCheck">
                                <input type="hidden" name="path" value="models">
                                <input type="hidden" name="attr" value="changeModel">
                                <button name="modelProjectSubmit" type="submit" class="button">change</button>
                            </form>
                        </div>

                        <?php elseif( $modelId == $sessionModelId ): ?>
                            <div class="projects-item-modelLink"><b>Change this model?</b></div>
                            <div class="projects-item-modelLink">
                                <form action="<?= APPLICATION_HOME; ?>" method="POST">
                                    <input type="hidden" name="modelId" value="<?= $modelId; ?>">
                                    <input type="hidden" name="projectId" value="<?= $projectId; ?>">
                                    <input type="hidden" name="changeCheck" value="accepted">
                                    <input type="hidden" name="path" value="models">
                                    <input type="hidden" name="attr" value="changeModel">
                                    <button name="modelProjectSubmit" type="submit" class="button">yes</button>
                                </form>
                            </div>

                            <div class="projects-item-modelLink">
                                <form action="<?= APPLICATION_HOME; ?>" method="POST">
                                    <input type="hidden" name="modelId" value="<?= $modelId; ?>">
                                    <input type="hidden" name="projectId" value="<?= $projectId; ?>">
                                    <input type="hidden" name="changeCheck" value="declined">
                                    <input type="hidden" name="path" value="models">
                                    <input type="hidden" name="attr" value="changeModel">
                                    <button name="modelProjectSubmit" type="submit" class="button">no</button>
                                </form>
                            </div>

                        <?php endif; ?>
                    </div>
                </div>

                <?php

            endforeach;

        else: ?>
            <div class="projects-message">No models available, create a new model in the left panel.</div>
        <?php endif;
    ?>
</div>