<?php
/**
 * Created by PhpStorm.
 * User: Ruben Hazenbosch
 * Date: 03-Aug-16
 * Time: 20:57
 */

use app\enterpriseArchitecture\IOXMLEAModel;
use app\enterpriseArchitecture\IOXMLEAScreenFactory;

$modelId = ( isset( $_SESSION['xmlModelId'] ) ? $_SESSION['xmlModelId'] : "" );

$orderedElements = ( new IOXMLEAScreenFactory( $modelId ) )->extractAndOrderElements();
$totalElements   = count( $orderedElements );

for( $i = 0; $i < $totalElements; $i++ ):

    if( $orderedElements[$i]['root'] === 'true' ):
        $element = ( new IOXMLEAScreenFactory( $orderedElements[$i] ) )->createIntro();
        print_r($element);

    else:
        $element = ( new IOXMLEAScreenFactory( $orderedElements[$i] ) )->createElement();

        print_r($element);

        echo '<pre>';
        print_r($orderedElements[$i]);

    endif;

endfor;