<?php
/**
 * Created by PhpStorm.
 * User: Ruben Hazenbosch
 * Date: 2-8-2016
 * Time: 18:54
 */

use app\lib\Project;

/**
 * Get the project data to display the project name
 */
$projectId      = ( isset( $_SESSION['project_id'] ) ? $_SESSION['project_id'] : "" );
$params         = array( "project_id" => $projectId );
$projectData    = ( new Project( "getProjectById" ) )->request( $params );
$projectName    = ( isset( $projectData['name'] ) ? $projectData['name'] : "" );

/**
 * Setup arrays to populate with projects and projects models.
 * Compare both array's and check if there are projects without a model
 * Store all projects without a model in the project select array.
 */
$projectsArray       = array();
$projectsModelsArray = array();
$projectSelectArray  = array();

$projects       = ( new Project( "getAllProjectsByUser" ) )->request( $params = null );
$projectsModels = ( new Project( "getAllProjectsModelsByUser" ) )->request( $params = null );

$i = 0;
foreach( $projects as $project ):
    $projectsArray[$i]['id']   = $project['id'];
    $projectsArray[$i]['name'] = $project['name'];
    $i++;
endforeach;

$j = 0;
foreach( $projectsModels as $projectsModel ):
    $projectsModelsArray[] = $projectsModel['project_id'];
    $j++;
endforeach;

$k = 0;
foreach( $projectsArray as $projectArray ):
    if( !in_array( $projectArray['id'], $projectsModelsArray ) ):

        $projectSelectArray[$k]['id'] = $projectArray['id'];
        $projectSelectArray[$k]['name'] = $projectArray['name'];
        $k++;
    endif;
endforeach;

/**
 * Display the project name when available
 */
?>
<div class="newModel">
    <div class="modelReport-Title">New model <?= ( !empty( $projectName ) ? "for " . $projectName : "" ) ?></div>
    <?php
    /**
     * Display a message when all projects have a model and disable the form
     */
    ?>
    <form action="<?= APPLICATION_HOME; ?>" method="post" enctype="multipart/form-data">
        <?php
        /**
         * Only show file select when a project is without a model
         */
            if( !empty( $projectSelectArray )  ): ?>
            <input type="file" name="xmlFile" id="xmlFile" value="" title="Kies een xml bestand.">
            <input type="hidden" name="path" value="models">
            <input type="hidden" name="attr" value="modelUpload">
        <?php
            endif;
            /**
             * Only show project select when a project name is empty and when a project is without a model
             */
            if( empty( $projectName ) && !empty( $projectSelectArray ) ): ?>
                <select name="project">
                    <option name="projectId" value="">Choose a project</option>
                <?php
                    foreach( $projectsArray as $projectArray ):
                        if( !in_array( $projectArray['id'], $projectsModelsArray ) ):
                            ?>
                            <option name="projectId" value="<?= $projectArray['id']; ?>"><?= $projectArray['name']; ?></option>
                            <?php
                        endif;
                    endforeach;
                ?>
                </select>
                <?php
            endif;
        /**
         * Only show submit when a project name isn't empty and when a project is without a model
         */
        if( !empty( $projectName ) || !empty( $projectSelectArray ) ): ?>
            <input type="submit" name="xmlFileUploadSubmit" value="Uploaden" title="Upload an xml file.">
        <?php endif; ?>

    </form>

    <?php
        if( isset( $_GET['modelUploadNoFile'] ) ):
            ?><div class="message">Please choose a file.</div><?php
        else:
            if( isset( $_GET['modelUploadNoProject'] ) ):
                ?><div class="message">Please choose a project.</div><?php
            elseif( isset( $_GET['modelUploadNameExists'] ) ):
                    ?><div class="message">Model name is already in use.</div><?php
            endif;
        endif;
    ?>
</div>