<?php
/**
 * Created by PhpStorm.
 * User: Ruben Hazenbosch
 * Date: 2-8-2016
 * Time: 21:11
 */

use app\enterpriseArchitecture\IOXMLEAModel;
use app\lib\Project;

/**
 * Get the last inserted model id
 * The model id is passed to the preview
 */
$xmlModelId = ( !empty( $_SESSION['xmlModelId'] ) ? $_SESSION['xmlModelId'] : "" );
$model      = ( new IOXMLEAModel( $xmlModelId ) )->getModel();
$modelName  = ( isset( $model['name'] ) ? $model['name'] : "No name found" );
$params     = array("model_id" => $xmlModelId);
$project    = ( new Project( "getProjectByModelId" ) )->request( $params );
$projectID  = ( !empty( $project['id'] ) ? $project['id'] : "" );
/**
 * Get the report session and unserialize it
 */
$report = unserialize( $_SESSION['xmlValidatorReport'] );

/**
 * Check if the report has a file exists flag, if so validation failed.
 */
$session_validation_severe = ( isset( $_SESSION['xmlModelErrorSevere'] ) ? $_SESSION['xmlModelErrorSevere'] : "" );
if( isset( $report['file_exists'] ) && $report['file_exists'] === true ):
    $fileExists = true;
    $validationMessage = "Model exists";
    $report['totalErrorTypes']['severe'] += 1;
endif;
/**
 * Check if there is an original file name
 */
$originalFileName = ( !empty( $report['originalFileName'] ) ? $report['originalFileName'] : "" );

?>


<div class="modelReport">

    <div class="modelReport-Title">XML Validation Report - Enterprise Architect Model</div>

    <div class="modelReport-container">

        <div class="modelReport-totalValidation <?= ( $report['validation']['valid'] === true && isset( $fileExists) !== true ? "totalValidationGreen" : "totalValidationRed" ) ?>">
            <?= ( isset( $fileExists ) && $fileExists === true ? $validationMessage : $report['validation']['message'] ); ?>
        </div>

        <div class="modelReport-validationInfo">
            <div class="modelReport-FileName">
                <strong>Validated model:</strong> <?= ( !empty( $modelName ) ? $modelName : "<span>No name found</span>" ); ?>
            </div>

            <?php if( isset( $report['validationDuration'] ) && $report['validationDuration'] !== 0 ): ?>
                <div class="modelReport-validationDuration">
                    <strong>Validation duration:</strong> <?= $report['validationDuration'].' seconds'; ?>
                </div>
                <div class="modelReport-validationDuration">
                    <form action="<?= APPLICATION_HOME; ?>" method="POST">
                        <input type="hidden" class="projectId" name="projectId" value="<?= $projectID; ?>">
                        <input type="hidden" name="path" value="models">
                        <input type="hidden" name="attr" value="model">
                        <button name="modelProjectSubmit" type="submit" class="button">preview</button>
                    </form>
                </div>
            <?php endif; ?>
        </div>

        <?php if( $report['validation']['value'] === false ): ?>
        <div class="modelReport-notification">
            <div class="modelReport-notification-title">Report notification:</div>
            <div class="modelReport-notification-msg">
                <p>
                    The model could not be processed, the database and preview could not be generated.
                    <br>
                    Go to <a href="<?= APPLICATION_HOME; ?>?models&model_id=<?= $xmlModelId; ?>">models</a> to change this model.
                </p>
            </div>
        </div>
       <?php else: ?>
            <div class="modelReport-notification">
                <div class="modelReport-notification-title">Report notification:</div>
                <div class="modelReport-notification-msg">
                    <p>
                        Model validation succeeded! A database has been created and the preview is available.
                        <br>
                        Go to <a href="<?= APPLICATION_HOME; ?>?models&model_id=<?= $xmlModelId; ?>">models</a> to change this model.
                    </p>
                </div>
            </div>
        <?php endif;?>

        <div class="modelReport-totalErrorTypes">

            <div class="modelReport-totalErrorType">
                <form action="" method="post">
                    <img src="./images/icons/checkgreen_icon.png">
                    <div class="modelReport-ErrorCount">
                        - <?= $report['totalErrorTypes']['valid']; ?> -
                    </div>
                    <?php if( isset( $_SESSION['xmlModelErrorValid'] ) && $_SESSION['xmlModelErrorValid'] === "hide" ): ?>
                        <input type="hidden" name="type" value="valid">
                        <input type="hidden" name="display" value="show">
                        <input type="hidden" name="model_id" value="<?= $xmlModelId; ?>">
                        <input type="hidden" name="path" value="models">
                        <input type="hidden" name="attr" value="modelErrorControl">
                        <button type="submit" name="submitTypeVisibility" value="show" title="Show">
                            <img src="images/icons/show_icon.png" alt="submit" title="Show" />
                        </button>
                    <?php else: ?>
                        <input type="hidden" name="type" value="valid">
                        <input type="hidden" name="display" value="hide">
                        <input type="hidden" name="model_id" value="<?= $xmlModelId; ?>">
                        <input type="hidden" name="path" value="models">
                        <input type="hidden" name="attr" value="modelErrorControl">
                        <button type="submit" name="submitTypeVisibility" value="hide" title="Hide">
                            <img src="images/icons/hide_icon.png" alt="submit" title="Hide" />
                        </button>
                    <?php endif; ?>
                </form>
            </div>

            <div class="modelReport-totalErrorType">
                <form action="" method="POST">
                    <img src="./images/icons/severe_icon.png">
                    <div class="modelReport-ErrorCount">
                        - <?= $report['totalErrorTypes']['severe']; ?> -
                    </div>
                    <?php if( isset( $_SESSION['xmlModelErrorSevere'] ) && $_SESSION['xmlModelErrorSevere'] === "hide" ): ?>
                        <input type="hidden" name="type" value="severe">
                        <input type="hidden" name="display" value="show">
                        <input type="hidden" name="model_id" value="<?= $xmlModelId; ?>">
                        <input type="hidden" name="path" value="models">
                        <input type="hidden" name="attr" value="modelErrorControl">
                        <button type="submit" name="submitTypeVisibility" value="show" title="Show">
                            <img src="images/icons/show_icon.png" alt="submit" title="Show" />
                        </button>
                    <?php else: ?>
                        <input type="hidden" name="type" value="severe">
                        <input type="hidden" name="display" value="hide">
                        <input type="hidden" name="model_id" value="<?= $xmlModelId; ?>">
                        <input type="hidden" name="path" value="models">
                        <input type="hidden" name="attr" value="modelErrorControl">
                        <button type="submit" name="submitTypeVisibility" value="hide" title="Hide">
                            <img src="images/icons/hide_icon.png" alt="submit" title="Hide" />
                        </button>
                    <?php endif; ?>
                </form>
            </div>

            <div class="modelReport-totalErrorType">
                <div class="modelReport-totalErrorType-box">
                    <form action="" method="POST">
                        <img src="./images/icons/red_cross_icon.png">
                        <div class="modelReport-ErrorCount">
                            -  <?= $report['totalErrorTypes']['error']; ?> -
                        </div>
                        <?php if( isset( $_SESSION['xmlModelErrorError'] ) && $_SESSION['xmlModelErrorError'] === "hide" ): ?>
                            <input type="hidden" name="type" value="error">
                            <input type="hidden" name="display" value="show">
                            <input type="hidden" name="model_id" value="<?= $xmlModelId; ?>">
                        <input type="hidden" name="path" value="models">
                        <input type="hidden" name="attr" value="modelErrorControl">
                            <button type="submit" name="submitTypeVisibility" value="show" title="Show">
                                <img src="images/icons/show_icon.png" alt="submit" title="Show" />
                            </button>
                        <?php else: ?>
                            <input type="hidden" name="type" value="error">
                            <input type="hidden" name="display" value="hide">
                            <input type="hidden" name="model_id" value="<?= $xmlModelId; ?>">
                        <input type="hidden" name="path" value="models">
                        <input type="hidden" name="attr" value="modelErrorControl">
                            <button type="submit" name="submitTypeVisibility" value="hide" title="Hide">
                                <img src="images/icons/hide_icon.png" alt="submit" title="Hide" />
                            </button>
                        <?php endif; ?>
                    </form>
                </div>
            </div>

            <div class="modelReport-totalErrorType">
                <form action="" method="POST">
                    <img src="./images/icons/warning_icon.png">
                    <div class="modelReport-ErrorCount">
                        - <?= $report['totalErrorTypes']['warning']; ?> -
                    </div>
                    <?php if( isset( $_SESSION['xmlModelErrorWarning'] ) && $_SESSION['xmlModelErrorWarning'] === "hide" ): ?>
                        <input type="hidden" name="type" value="warning">
                        <input type="hidden" name="display" value="show">
                        <input type="hidden" name="model_id" value="<?= $xmlModelId; ?>">
                        <input type="hidden" name="path" value="models">
                        <input type="hidden" name="attr" value="modelErrorControl">
                        <button type="submit" name="submitTypeVisibility" value="show" title="Show">
                            <img src="images/icons/show_icon.png" alt="submit" title="Show" />
                        </button>
                    <?php else: ?>
                        <input type="hidden" name="type" value="warning">
                        <input type="hidden" name="display" value="hide">
                        <input type="hidden" name="model_id" value="<?= $xmlModelId; ?>">
                        <input type="hidden" name="path" value="models">
                        <input type="hidden" name="attr" value="modelErrorControl">
                        <button type="submit" name="submitTypeVisibility" value="hide" title="Hide">
                            <img src="images/icons/hide_icon.png" alt="submit" title="Hide"/>
                        </button>
                    <?php endif; ?>
                </form>
            </div>

            <div class="modelReport-totalErrorType">
                <form action="" method="POST">
                    <img src="./images/icons/info_icon_blue.png">
                    <div class="modelReport-ErrorCount">
                        - <?= $report['totalErrorTypes']['info']; ?> -
                    </div>
                    <?php if( isset( $_SESSION['xmlModelErrorInfo'] ) && $_SESSION['xmlModelErrorInfo'] === "hide" ): ?>
                        <input type="hidden" name="type" value="info">
                        <input type="hidden" name="display" value="show">
                        <input type="hidden" name="model_id" value="<?= $xmlModelId; ?>">
                        <input type="hidden" name="path" value="models">
                        <input type="hidden" name="attr" value="modelErrorControl">
                        <button type="submit" name="submitTypeVisibility" value="show" title="Show">
                            <img src="images/icons/show_icon.png" alt="submit" title="Show" />
                        </button>
                    <?php else: ?>
                        <input type="hidden" name="type" value="info">
                        <input type="hidden" name="display" value="hide">
                        <input type="hidden" name="model_id" value="<?= $xmlModelId; ?>">
                        <input type="hidden" name="path" value="models">
                        <input type="hidden" name="attr" value="modelErrorControl">
                        <button type="submit" name="submitTypeVisibility" value="hide" title="Hide">
                            <img src="images/icons/hide_icon.png" alt="submit" title="Hide" />
                        </button>
                    <?php endif; ?>
                </form>
            </div>

        </div>

        <div class="modelReport-item modelReport-grayBack">
            <div class="modelReport-item-img">
                &nbsp;Type
            </div>
            <div class="modelReport-item-name">Subject</div>
            <div class="modelReport-item-value">Information</div>
            <div class="modelReport-item-message">Description</div>
        </div>

        <?php if( isset( $fileExists ) && $fileExists === true && $session_validation_severe !== "hide" ): ?>
            <div class="modelReport-item">
                <div class="modelReport-item-img">
                    <img src="./images/icons/severe_icon.png"">
                    <div class="modelReport-item-type"> severe</div>
                </div>
                <div class="modelReport-item-name">Model already exists</div>
                <div class="modelReport-item-value">exists</div>
                <div class="modelReport-item-message">Duplicate model found.</div>
            </div>

            <div class="modelReport-item">
                <div class="modelReport-item-img"></div>
                <div class="modelReport-item-info">
                    <img src="./images/icons/arrow_right_up.png">
                    <div class="">
                        Duplicate model: the uploaded model already exists, could not process the model.
                    </div>
                </div>
            </div>

        <?php endif; ?>

        <?php

        /**
         * Show all report items, excluding the validation array.
         */
        if( !empty( $report ) ):

            $icons = [
                'model_validation' => [
                    'warning'     => 'warning_icon.png',
                    'info'        => 'info_icon_blue.png',
                    'severe'      => 'severe_icon.png',
                    'valid'       => 'checkgreen_icon.png',
                    'error'       => 'error_icon.png'
                ],

                'other' => []
            ];

            foreach( $report as $key => $v ):

                if( !empty( $report[$key]['type'] ) && $key !== "validation" && $key !== 'totalErrorTypes' ):

                    $sessionType = ( isset( $_SESSION['xmlModelError'.( ucfirst( $report[$key]['type'] ) )] ) ? $_SESSION['xmlModelError'.( ucfirst( $report[$key]['type'] ) )] : "");
                    if( !empty( $sessionType && $sessionType === "hide" ) ):

                    else:

                        ?>
                        <?php $type = $report[$key]['type']; ?>
                        <div class="modelReport-item">
                            <div class="modelReport-item-img">
                                <img src="./images/icons/<?= $icons['model_validation'][$type] ?>">
                                <div class="modelReport-item-type"> <?= $report[$key]['type']; ?></div>
                            </div>
                            <div class="modelReport-item-name"><?= $report[$key]['name']; ?></div>
                            <div class="modelReport-item-value"><?= $report[$key]['value']; ?></div>
                            <div class="modelReport-item-message"><?= $report[$key]['message']; ?></div>
                        </div>

                        <?php if( $report[$key]['valid'] === false ): ?>
                        <div class="modelReport-item">
                            <div class="modelReport-item-img"></div>
                            <div class="modelReport-item-info">
                                <img src="./images/icons/arrow_right_up.png">
                                <div class="">
                                    <?= $report[$key]['info']; ?>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>

                        <?php

                    endif;

                endif;

            endforeach;

        endif;

        ?>

    </div>

</div>

